### ISSUE TITLE
1d Persistent Homology Example

### ISSUE THREAD

**Issue by xchhuang** [gjkoplik/pers-hom-examples#1]
Hi @gjkoplik,

I am interested in how you get the following figure: it seems like you are doing an optimization to make the initial points form three circles, but what is the objective function ? Do you define a target Persistence Diagram ? Thanks in advance.

![fig5](https://user-images.githubusercontent.com/22114321/95314272-5e482a80-0891-11eb-9e15-42b98e0070fa.gif)

**Comment by gjkoplik** [comment]
Hi @xchhuang,

The points converge on three circles by moving along a vector field I constructed that by design brings all points to the three hard-coded circles. There is no target PD-- the right figure is simply the result of calculating 1d persistent homology at each time step. Hope that helps!

**Comment by xchhuang** [comment]
Hi @gjkoplik,

Good to know that. Thank you for your clarification.
